package trabalhofinal;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer Nitro
 */
public class Chat extends javax.swing.JPanel {

    /**
     * Creates new form Chat
     */
    public Chat() {
        initComponents();
    }

    Chat(String nomeDestino) {
        this.nomeDestino.setText(nomeDestino);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        campoMensagem = new javax.swing.JTextField();
        botaoEnviar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatBox = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        nomeUsuario = new javax.swing.JLabel();
        nomeDestino = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeDestino1 = new javax.swing.JLabel();

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setEnabled(false);
        jPanel1.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel2.setMinimumSize(new java.awt.Dimension(79, 30));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        campoMensagem.setEnabled(false);
        campoMensagem.setPreferredSize(new java.awt.Dimension(10, 20));
        campoMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMensagemActionPerformed(evt);
            }
        });
        jPanel2.add(campoMensagem);

        botaoEnviar.setText("Enviar");
        botaoEnviar.setEnabled(false);
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });
        jPanel2.add(botaoEnviar);

        jPanel1.add(jPanel2, java.awt.BorderLayout.SOUTH);

        chatBox.setEditable(false);
        chatBox.setColumns(20);
        chatBox.setRows(5);
        chatBox.setEnabled(false);
        chatBox.setFocusable(false);
        jScrollPane1.setViewportView(chatBox);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setEnabled(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(570, 100));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeUsuario.setPreferredSize(new java.awt.Dimension(41, 18));
        jPanel3.add(nomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 430, -1));

        nomeDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeDestino.setPreferredSize(new java.awt.Dimension(0, 17));
        jPanel3.add(nomeDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 460, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nome de usuário: ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Destinatario:");
        jLabel2.setEnabled(false);
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Status:");
        jLabel3.setEnabled(false);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        nomeDestino1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeDestino1.setPreferredSize(new java.awt.Dimension(0, 17));
        jPanel3.add(nomeDestino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 500, -1));

        jPanel5.add(jPanel3, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMensagemActionPerformed
        if (!campoMensagem.getText().equals("")){
            botaoEnviarActionPerformed(evt);

        }
    }//GEN-LAST:event_campoMensagemActionPerformed

    private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarActionPerformed
        String a = campoMensagem.getText();
        chatBox.append(nomeUsuario.getText()+"->"+a+"\n");
        try {
            Servidor.getInstance().enviarMensagemPara("Luciano", a);
            campoMensagem.setText("");
        } catch (IOException ex) {
//            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botaoEnviarActionPerformed

    public void ativar(boolean a) {
        jLabel2.setEnabled(a);
        jLabel3.setEnabled(a);
        chatBox.setEnabled(a);
        campoMensagem.setEnabled(a);
        botaoEnviar.setEnabled(a);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JTextField campoMensagem;
    private javax.swing.JTextArea chatBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomeDestino;
    private javax.swing.JLabel nomeDestino1;
    private javax.swing.JLabel nomeUsuario;
    // End of variables declaration//GEN-END:variables
}
